// pages/SymptomTracker.jsx
// ─── Premium Health Journal with Real Claude AI ───────────────
// AI suggestions are generated by Claude based on actual user input
// No more hardcoded strings — every suggestion is unique and personal
// ─────────────────────────────────────────────────────────────

import { useState, useEffect, useRef } from "react";
import { useNavigate } from "react-router-dom";
import axios from "axios";
import { motion, AnimatePresence } from "framer-motion";
import {
  Sparkles, Calendar, ChevronDown, Mic, MicOff,
  TrendingUp, TrendingDown, Minus, Activity,
  Heart, Brain, AlertCircle, CheckCircle, X,
  BookOpen, Flame, Zap,
} from "lucide-react";
import { predictDisease } from "../../services/aiService";

// ── Design tokens ─────────────────────────────────────────────
const FF   = "'DM Sans', 'Segoe UI', sans-serif";
const NAVY = "#0d1b2a";
const TEAL = "#0a7e6e";

const MOODS = [
  { key: "Happy",   emoji: "😊", color: "#f59e0b", bg: "#fffbeb", dark: "#92400e" },
  { key: "Neutral", emoji: "😐", color: "#64748b", bg: "#f8fafc", dark: "#334155" },
  { key: "Sad",     emoji: "😢", color: "#3b82f6", bg: "#eff6ff", dark: "#1e40af" },
  { key: "Anxious", emoji: "😰", color: "#8b5cf6", bg: "#f5f3ff", dark: "#5b21b6" },
  { key: "Angry",   emoji: "😤", color: "#ef4444", bg: "#fff1f2", dark: "#991b1b" },
  { key: "Tired",   emoji: "😴", color: "#0ea5e9", bg: "#f0f9ff", dark: "#0c4a6e" },
  { key: "Sick",    emoji: "🤒", color: "#10b981", bg: "#ecfdf5", dark: "#065f46" },
  { key: "Stressed",emoji: "😣", color: "#f97316", bg: "#fff7ed", dark: "#9a3412" },
];

const getMood = (key) => MOODS.find(m => m.key === key) || MOODS[1];

async function getAISuggestion(symptoms, mood, notes) {
  return await predictDisease({
    symptomEntries: [
      {
        date: new Date().toISOString().split("T")[0],
        mood,
        symptoms,
        notes,
      },
    ],
  });
}

// ── Streak calculator ─────────────────────────────────────────
function getStreak(entries) {
  if (!entries.length) return 0;
  const dates = [...new Set(entries.map(e => e.date?.split("T")[0]))].sort().reverse();
  let streak = 0;
  let current = new Date();
  current.setHours(0,0,0,0);
  for (const d of dates) {
    const entryDate = new Date(d);
    const diff = Math.round((current - entryDate) / 86400000);
    if (diff <= 1) { streak++; current = entryDate; }
    else break;
  }
  return streak;
}

// ── Mood trend ────────────────────────────────────────────────
function getMoodTrend(entries) {
  if (entries.length < 3) return "flat";
  const positiveMoods = ["Happy", "Neutral"];
  const recent  = entries.slice(0, 3).filter(e => positiveMoods.includes(e.mood)).length;
  const older   = entries.slice(3, 6).filter(e => positiveMoods.includes(e.mood)).length;
  if (recent > older) return "up";
  if (recent < older) return "down";
  return "flat";
}

// ── AI Suggestion Card ────────────────────────────────────────
function AISuggestionCard({ suggestion, mood, onClose }) {
  const md = getMood(mood);

  return (
    <motion.div
      initial={{ opacity: 0, y: 16, scale: 0.97 }}
      animate={{ opacity: 1, y: 0, scale: 1 }}
      exit={{ opacity: 0, y: -10 }}
      style={{
        background: "white",
        borderRadius: 20,
        border: `1.5px solid ${md.color}25`,
        boxShadow: `0 8px 32px ${md.color}15`,
        overflow: "hidden",
        marginTop: 14,
      }}
    >
      {/* Header */}
      <div style={{ background: `linear-gradient(135deg, ${md.color}15, ${md.color}05)`, padding: "14px 18px", borderBottom: `1px solid ${md.color}15`, display: "flex", justifyContent: "space-between", alignItems: "center" }}>
        <div style={{ display: "flex", alignItems: "center", gap: 8 }}>
          <div style={{ width: 30, height: 30, borderRadius: 9, background: `linear-gradient(135deg, ${md.color}, ${md.color}cc)`, display: "flex", alignItems: "center", justifyContent: "center" }}>
            <Sparkles size={14} color="white" />
          </div>
          <div>
            <p style={{ fontWeight: 800, color: NAVY, margin: 0, fontSize: "0.82rem" }}>✦ AI-Assisted Analysis</p>
            <p style={{ color: "#94a3b8", fontSize: "0.65rem", margin: 0 }}>Personalized for your entry</p>
          </div>
        </div>
        {onClose && <button onClick={onClose} style={{ background: "none", border: "none", cursor: "pointer", color: "#94a3b8" }}><X size={16} /></button>}
      </div>

      <div style={{ padding: "16px 18px", display: "flex", flexDirection: "column", gap: 12 }}>

        {/* Doctor alert */}
        {suggestion.shouldSeeDoctor && (
          <div style={{ background: "#fef2f2", borderRadius: 12, padding: "10px 14px", border: "1px solid rgba(220,38,38,0.2)", display: "flex", gap: 9, alignItems: "flex-start" }}>
            <AlertCircle size={15} color="#dc2626" style={{ flexShrink: 0, marginTop: 1 }} />
            <div>
              <p style={{ fontWeight: 800, color: "#dc2626", margin: "0 0 2px", fontSize: "0.78rem" }}>Consider Seeing a Doctor</p>
              <p style={{ color: "#dc2626", fontSize: "0.74rem", margin: 0, opacity: 0.85 }}>{suggestion.doctorReason}</p>
            </div>
          </div>
        )}

        {/* Main advice */}
        <div style={{ background: `${md.color}08`, borderRadius: 12, padding: "12px 14px", border: `1px solid ${md.color}15` }}>
          <p style={{ fontSize: "0.84rem", color: "#1e293b", margin: 0, lineHeight: 1.7, fontStyle: "italic" }}>
            "{suggestion.mainAdvice}"
          </p>
        </div>

        {/* 3-column cards */}
        <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr 1fr", gap: 8 }}>
          {[
            { icon: <Zap size={12} />, label: "Do Right Now", value: suggestion.immediateAction, color: "#f59e0b" },
            { icon: <AlertCircle size={12} />, label: "Watch For", value: suggestion.watchOut, color: "#ef4444" },
            { icon: <Heart size={12} />, label: "Lifestyle Tip", value: suggestion.lifestyleTip, color: TEAL },
          ].map((c, i) => (
            <div key={i} style={{ background: "#f8fafc", borderRadius: 11, padding: "10px 11px", border: "1px solid #f0f4f8" }}>
              <div style={{ display: "flex", alignItems: "center", gap: 5, color: c.color, marginBottom: 5 }}>
                {c.icon}
                <span style={{ fontSize: "0.6rem", fontWeight: 800, textTransform: "uppercase", letterSpacing: "0.07em" }}>{c.label}</span>
              </div>
              <p style={{ fontSize: "0.73rem", color: "#334155", margin: 0, lineHeight: 1.5 }}>{c.value}</p>
            </div>
          ))}
        </div>

        {/* Encouragement */}
        <div style={{ background: `linear-gradient(135deg, ${NAVY}08, ${TEAL}08)`, borderRadius: 11, padding: "10px 14px", display: "flex", alignItems: "center", gap: 8 }}>
          <span style={{ fontSize: "1rem" }}>{md.emoji}</span>
          <p style={{ fontSize: "0.78rem", color: "#334155", margin: 0, fontWeight: 500, lineHeight: 1.5 }}>{suggestion.encouragement}</p>
        </div>

        {/* Urgency badge */}
        <div style={{ display: "flex", justifyContent: "flex-end" }}>
          <span style={{
            padding: "3px 10px", borderRadius: 99, fontSize: "0.62rem", fontWeight: 800,
            background: suggestion.urgency === "high" ? "#fef2f2" : suggestion.urgency === "medium" ? "#fffbeb" : "#f0fdf9",
            color: suggestion.urgency === "high" ? "#dc2626" : suggestion.urgency === "medium" ? "#b45309" : "#16a34a",
            border: `1px solid ${suggestion.urgency === "high" ? "rgba(220,38,38,0.2)" : suggestion.urgency === "medium" ? "rgba(180,83,9,0.2)" : "rgba(22,163,74,0.2)"}`,
          }}>
            {suggestion.urgency === "high" ? "🔴 Needs Attention" : suggestion.urgency === "medium" ? "🟡 Monitor Closely" : "🟢 All Good"}
          </span>
        </div>
      </div>
    </motion.div>
  );
}

// ── Entry Card ────────────────────────────────────────────────
function EntryCard({ entry, index }) {
  const [expanded, setExpanded] = useState(false);
  const md = getMood(entry.mood);
  const hasAI = entry.aiSuggestion;

  return (
    <motion.div
      initial={{ opacity: 0, y: 12 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ delay: index * 0.04 }}
      style={{ background: "white", borderRadius: 20, border: "1px solid #e8edf2", boxShadow: "0 2px 12px rgba(0,0,0,0.04)", overflow: "hidden" }}
    >
      {/* Left accent bar */}
      <div style={{ display: "flex" }}>
        <div style={{ width: 4, background: `linear-gradient(to bottom, ${md.color}, ${md.color}40)`, flexShrink: 0 }} />
        <div style={{ flex: 1, padding: "1.2rem 1.4rem" }}>

          {/* Top row */}
          <div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start", marginBottom: 8, flexWrap: "wrap", gap: 8 }}>
            <div>
              <h3 style={{ fontWeight: 700, color: NAVY, margin: 0, fontSize: "0.95rem" }}>{entry.symptoms}</h3>
              <p style={{ color: "#94a3b8", fontSize: "0.72rem", margin: "2px 0 0", display: "flex", alignItems: "center", gap: 4 }}>
                <Calendar size={10} />{entry.date?.split("T")[0] || entry.date}
              </p>
            </div>
            <span style={{ padding: "4px 12px", borderRadius: 99, fontSize: "0.75rem", fontWeight: 700, background: md.bg, color: md.color, border: `1px solid ${md.color}25` }}>
              {md.emoji} {entry.mood}
            </span>
          </div>

          {/* Notes */}
          {entry.notes && (
            <p style={{ color: "#4a6070", fontSize: "0.82rem", margin: "0 0 10px", lineHeight: 1.6 }}>{entry.notes}</p>
          )}

          {/* AI suggestion preview */}
          {hasAI && (
            <div
              onClick={() => setExpanded(e => !e)}
              style={{ background: `${md.color}08`, border: `1px solid ${md.color}18`, borderRadius: 12, padding: "9px 13px", cursor: "pointer", display: "flex", justifyContent: "space-between", alignItems: "center", gap: 8 }}
            >
              <div style={{ display: "flex", alignItems: "center", gap: 7, flex: 1, minWidth: 0 }}>
                <Sparkles size={12} color={md.color} style={{ flexShrink: 0 }} />
                <p style={{ fontSize: "0.78rem", color: md.dark, margin: 0, fontWeight: 500, lineHeight: 1.4, overflow: "hidden", display: "-webkit-box", WebkitLineClamp: expanded ? "unset" : 1, WebkitBoxOrient: "vertical" }}>
                  {entry.aiSuggestion.mainAdvice}
                </p>
              </div>
              <ChevronDown size={14} color={md.color} style={{ flexShrink: 0, transform: expanded ? "rotate(180deg)" : "none", transition: "transform 0.2s" }} />
            </div>
          )}

          {/* Expanded AI content */}
          <AnimatePresence>
            {expanded && hasAI && (
              <motion.div initial={{ height: 0, opacity: 0 }} animate={{ height: "auto", opacity: 1 }} exit={{ height: 0, opacity: 0 }} style={{ overflow: "hidden" }}>
                <AISuggestionCard suggestion={entry.aiSuggestion} mood={entry.mood} />
              </motion.div>
            )}
          </AnimatePresence>

          {/* No AI — static fallback */}
          {!hasAI && entry.moodSuggestion && (
            <div style={{ background: "#f0fdf9", border: "1px solid rgba(10,126,110,0.1)", borderRadius: 12, padding: "9px 13px" }}>
              <p style={{ fontSize: "0.78rem", color: TEAL, fontWeight: 500, margin: 0 }}>💡 {entry.moodSuggestion}</p>
            </div>
          )}
        </div>
      </div>
    </motion.div>
  );
}

// ── MAIN COMPONENT ────────────────────────────────────────────
export default function SymptomTracker() {
  const [formData,   setFormData]   = useState({ mood: "", symptoms: "", notes: "", date: new Date().toISOString().split("T")[0] });
  const [entries,    setEntries]    = useState([]);
  const [patientId,  setPatientId]  = useState(null);
  const [submitting, setSubmitting] = useState(false);
  const [aiLoading,  setAiLoading]  = useState(false);
  const [freshAI,    setFreshAI]    = useState(null);  // AI result for just-submitted entry
  const [listening,  setListening]  = useState(false); // voice input
  const recognitionRef = useRef(null);
  const navigate = useNavigate();

  useEffect(() => {
    let id = localStorage.getItem("patientId");
    if (!id) { navigate("/login"); return; }
    id = id.replace(/^"|"$/g, "");
    setPatientId(id);
    fetchSymptoms(id);
  }, [navigate]);

  const fetchSymptoms = async (pid) => {
    try {
      const token = localStorage.getItem("token");
      const res = await axios.get(`/api/symptoms/patient/${pid}`, { headers: { Authorization: `Bearer ${token}` } });
      setEntries(res.data);
    } catch (err) { console.error(err); }
  };

  // ── Voice input (Web Speech API) ──────────────────────────
  const toggleVoice = () => {
    if (!("webkitSpeechRecognition" in window || "SpeechRecognition" in window)) {
      alert("Voice input not supported in this browser. Try Chrome.");
      return;
    }
    if (listening) {
      recognitionRef.current?.stop();
      setListening(false);
      return;
    }
    const SR = window.SpeechRecognition || window.webkitSpeechRecognition;
    const rec = new SR();
    rec.lang = "en-IN";
    rec.interimResults = false;
    rec.onresult = (e) => {
      const transcript = e.results[0][0].transcript;
      setFormData(f => ({ ...f, symptoms: transcript }));
      setListening(false);
    };
    rec.onerror = () => setListening(false);
    rec.onend   = () => setListening(false);
    rec.start();
    recognitionRef.current = rec;
    setListening(true);
  };

  // ── Submit ────────────────────────────────────────────────
  const handleSubmit = async (e) => {
    e.preventDefault();
    if (!formData.mood || !formData.symptoms) return alert("Mood and symptoms are required.");
    setSubmitting(true);
    setFreshAI(null);

    try {
      const token = localStorage.getItem("token");

      // Save entry first
      const res = await axios.post(
        `/api/symptoms/add`,
        { ...formData, patient: patientId },
        { headers: { Authorization: `Bearer ${token}` } }
      );

      // Then get AI suggestion
      setAiLoading(true);
      let aiSuggestion = null;
      try {
        const aiResult = await getAISuggestion(
          formData.symptoms,
          formData.mood,
          formData.notes
        );

        // map backend → UI format
        aiSuggestion = {
          mainAdvice: aiResult.patternSummary,
          immediateAction: aiResult.nextSteps,
          watchOut: aiResult.redFlags?.[0] || "No immediate concerns",
          lifestyleTip: aiResult.predictions?.[0]?.recommendation || "Maintain healthy habits",
          urgency: aiResult.overallRisk === "high" ? "high" : "low",
          encouragement: "You're taking a great step by tracking your health.",
          shouldSeeDoctor: aiResult.overallRisk === "high",
          doctorReason: aiResult.redFlags?.[0] || null
        };
        setFreshAI({ suggestion: aiSuggestion, mood: formData.mood });
      } catch (aiErr) {
        console.error("AI suggestion failed:", aiErr);
      } finally {
        setAiLoading(false);
      }

      // Add to entries list with AI data
      setEntries(prev => [{ ...res.data, aiSuggestion }, ...prev]);
      setFormData(f => ({ ...f, symptoms: "", notes: "", mood: "" }));

    } catch (err) {
      console.error(err);
      alert("Failed to save entry. Try again.");
    } finally {
      setSubmitting(false);
    }
  };

  const streak = getStreak(entries);
  const trend  = getMoodTrend(entries);
  const selectedMood = getMood(formData.mood);

  const inputStyle = {
    width: "100%",
    padding: "11px 14px",
    borderRadius: 10,
    border: "1.5px solid #e2e8f0",
    background: "#f8fafc",
    fontSize: "0.875rem",
    color: NAVY,
    outline: "none",
    fontFamily: FF,
    boxSizing: "border-box",
    transition: "border-color 0.2s",
  };

  const labelStyle = {
    display: "block",
    fontSize: "0.7rem",
    fontWeight: 700,
    color: "#64748b",
    letterSpacing: "0.07em",
    textTransform: "uppercase",
    marginBottom: 6,
  };

  return (
    <div style={{ minHeight: "100vh", background: "linear-gradient(160deg, #f0f9f7 0%, #ffffff 60%, #eef4fb 100%)", fontFamily: FF, paddingTop: "5.5rem", paddingBottom: "4rem" }}>
      <div style={{ maxWidth: 1100, margin: "0 auto", padding: "0 1.5rem" }}>

        {/* ── Page Header ── */}
        <motion.div initial={{ opacity: 0, y: -10 }} animate={{ opacity: 1, y: 0 }} style={{ marginBottom: "2rem" }}>
          <div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-end", flexWrap: "wrap", gap: 14 }}>
            <div>
              <h1 style={{ fontSize: "clamp(1.8rem, 3vw, 2.4rem)", fontWeight: 800, color: NAVY, letterSpacing: "-0.03em", margin: 0 }}>
                Health Journal
              </h1>
              <p style={{ color: "#64748b", marginTop: 5, margin: "5px 0 0" }}>Log your daily health and get clinically-informed insights via CareAI.</p>
            </div>

            {/* Stats bar */}
            <div style={{ display: "flex", gap: 10, flexWrap: "wrap" }}>
              {/* Streak */}
              <div style={{ background: "white", borderRadius: 14, padding: "10px 16px", border: "1px solid #e8edf2", display: "flex", alignItems: "center", gap: 8, boxShadow: "0 2px 8px rgba(0,0,0,0.04)" }}>
                <Flame size={16} color="#f59e0b" />
                <div>
                  <p style={{ fontWeight: 800, color: NAVY, margin: 0, fontSize: "1rem", lineHeight: 1 }}>{streak}</p>
                  <p style={{ fontSize: "0.6rem", color: "#94a3b8", margin: 0, fontWeight: 600 }}>DAY STREAK</p>
                </div>
              </div>

              {/* Total entries */}
              <div style={{ background: "white", borderRadius: 14, padding: "10px 16px", border: "1px solid #e8edf2", display: "flex", alignItems: "center", gap: 8, boxShadow: "0 2px 8px rgba(0,0,0,0.04)" }}>
                <BookOpen size={16} color={TEAL} />
                <div>
                  <p style={{ fontWeight: 800, color: NAVY, margin: 0, fontSize: "1rem", lineHeight: 1 }}>{entries.length}</p>
                  <p style={{ fontSize: "0.6rem", color: "#94a3b8", margin: 0, fontWeight: 600 }}>ENTRIES</p>
                </div>
              </div>

              {/* Mood trend */}
              <div style={{ background: "white", borderRadius: 14, padding: "10px 16px", border: "1px solid #e8edf2", display: "flex", alignItems: "center", gap: 8, boxShadow: "0 2px 8px rgba(0,0,0,0.04)" }}>
                {trend === "up"   ? <TrendingUp size={16} color="#16a34a" /> :
                 trend === "down" ? <TrendingDown size={16} color="#dc2626" /> :
                 <Minus size={16} color="#94a3b8" />}
                <div>
                  <p style={{ fontWeight: 800, color: trend === "up" ? "#16a34a" : trend === "down" ? "#dc2626" : "#94a3b8", margin: 0, fontSize: "0.8rem", lineHeight: 1 }}>
                    {trend === "up" ? "Improving" : trend === "down" ? "Declining" : "Stable"}
                  </p>
                  <p style={{ fontSize: "0.6rem", color: "#94a3b8", margin: 0, fontWeight: 600 }}>MOOD TREND</p>
                </div>
              </div>
            </div>
          </div>
        </motion.div>

        {/* ── Main layout ── */}
        <div style={{ display: "grid", gridTemplateColumns: "340px 1fr", gap: 24, alignItems: "start" }}>

          {/* ── Form ── */}
          <div style={{ position: "sticky", top: 88 }}>
            <motion.div
              initial={{ opacity: 0, x: -16 }}
              animate={{ opacity: 1, x: 0 }}
              style={{ background: "white", borderRadius: 22, padding: "1.8rem", border: "1px solid #e8edf2", boxShadow: "0 4px 20px rgba(0,0,0,0.06)" }}
            >
              <h2 style={{ fontWeight: 800, color: NAVY, margin: "0 0 1.4rem", fontSize: "1rem" }}>Log Today's Health</h2>

              <form onSubmit={handleSubmit} style={{ display: "flex", flexDirection: "column", gap: 14 }}>

                {/* Date */}
                <div>
                  <label style={labelStyle}>Date</label>
                  <input type="date" value={formData.date}
                    onChange={e => setFormData(f => ({ ...f, date: e.target.value }))}
                    style={inputStyle}
                  />
                </div>

                {/* Mood selector — visual pills */}
                <div>
                  <label style={labelStyle}>How are you feeling?</label>
                  <div style={{ display: "grid", gridTemplateColumns: "repeat(4, 1fr)", gap: 6 }}>
                    {MOODS.map(m => (
                      <button key={m.key} type="button"
                        onClick={() => setFormData(f => ({ ...f, mood: m.key }))}
                        style={{
                          padding: "8px 4px",
                          borderRadius: 12,
                          border: `2px solid ${formData.mood === m.key ? m.color : "#e2e8f0"}`,
                          background: formData.mood === m.key ? m.bg : "#f8fafc",
                          cursor: "pointer",
                          display: "flex",
                          flexDirection: "column",
                          alignItems: "center",
                          gap: 3,
                          transition: "all 0.15s",
                          transform: formData.mood === m.key ? "scale(1.05)" : "scale(1)",
                        }}>
                        <span style={{ fontSize: "1.2rem" }}>{m.emoji}</span>
                        <span style={{ fontSize: "0.6rem", fontWeight: 700, color: formData.mood === m.key ? m.color : "#94a3b8" }}>{m.key}</span>
                      </button>
                    ))}
                  </div>
                </div>

                {/* Symptoms with voice */}
                <div>
                  <label style={labelStyle}>Symptoms</label>
                  <div style={{ position: "relative" }}>
                    <input
                      type="text"
                      value={formData.symptoms}
                      onChange={e => setFormData(f => ({ ...f, symptoms: e.target.value }))}
                      placeholder={listening ? "🎤 Listening..." : "e.g. Headache, fatigue, nausea"}
                      style={{ ...inputStyle, paddingRight: 44, borderColor: listening ? "#ef4444" : "#e2e8f0" }}
                    />
                    <button type="button" onClick={toggleVoice}
                      style={{ position: "absolute", right: 10, top: "50%", transform: "translateY(-50%)", background: "none", border: "none", cursor: "pointer", color: listening ? "#ef4444" : "#94a3b8", display: "flex", alignItems: "center" }}>
                      {listening ? <MicOff size={16} /> : <Mic size={16} />}
                    </button>
                  </div>
                  <p style={{ fontSize: "0.62rem", color: "#94a3b8", margin: "4px 0 0" }}>Or tap 🎤 to speak your symptoms</p>
                </div>

                {/* Notes */}
                <div>
                  <label style={labelStyle}>Additional Notes</label>
                  <textarea
                    value={formData.notes}
                    onChange={e => setFormData(f => ({ ...f, notes: e.target.value }))}
                    placeholder="Any additional details, triggers, or context..."
                    rows={3}
                    style={{ ...inputStyle, resize: "vertical" }}
                  />
                </div>

                {/* Submit */}
                <button type="submit" disabled={submitting || aiLoading}
                  style={{
                    padding: "13px",
                    borderRadius: 13,
                    background: formData.mood && formData.symptoms
                      ? `linear-gradient(135deg, ${selectedMood.color}, ${selectedMood.color}cc)`
                      : "linear-gradient(135deg, #0a7e6e, #0d9488)",
                    color: "white",
                    fontWeight: 800,
                    fontSize: "0.9rem",
                    border: "none",
                    cursor: submitting || aiLoading ? "not-allowed" : "pointer",
                    fontFamily: FF,
                    boxShadow: `0 6px 20px ${formData.mood ? selectedMood.color : TEAL}30`,
                    opacity: submitting || aiLoading ? 0.8 : 1,
                    transition: "all 0.3s",
                    display: "flex",
                    alignItems: "center",
                    justifyContent: "center",
                    gap: 8,
                  }}>
                  {submitting ? (
                    <><div style={{ width: 14, height: 14, border: "2px solid white", borderTopColor: "transparent", borderRadius: "50%", animation: "spin 0.7s linear infinite" }} /> Saving…</>
                  ) : aiLoading ? (
                    <><Sparkles size={15} /> Getting AI Insights…</>
                  ) : (
                    <><Sparkles size={15} /> Save & Get AI Insights</>
                  )}
                </button>
              </form>
            </motion.div>

            {/* Fresh AI result — shown below form */}
            <AnimatePresence>
              {freshAI && (
                <AISuggestionCard
                  suggestion={freshAI.suggestion}
                  mood={freshAI.mood}
                  onClose={() => setFreshAI(null)}
                />
              )}
            </AnimatePresence>
          </div>

          {/* ── Entries ── */}
          <div>
            <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: "1.2rem" }}>
              <h2 style={{ fontWeight: 800, color: NAVY, margin: 0, fontSize: "1rem" }}>
                Recent Entries
              </h2>
              {entries.length > 0 && (
                <span style={{ fontSize: "0.72rem", color: "#94a3b8", fontWeight: 600 }}>
                  {entries.length} total entries
                </span>
              )}
            </div>

            {entries.length === 0 ? (
              <div style={{ background: "white", borderRadius: 20, padding: "4rem", textAlign: "center", color: "#94a3b8", border: "2px dashed #e2e8f0" }}>
                <div style={{ fontSize: "2.5rem", marginBottom: 12 }}>📋</div>
                <p style={{ fontWeight: 700, margin: "0 0 6px", color: NAVY }}>No entries yet</p>
                <p style={{ fontSize: "0.82rem", margin: 0 }}>Start logging your health to get personalized AI insights.</p>
              </div>
            ) : (
              <div style={{ display: "flex", flexDirection: "column", gap: 12 }}>
                {entries.map((entry, i) => (
                  <EntryCard key={entry._id || i} entry={entry} index={i} />
                ))}
              </div>
            )}
          </div>
        </div>
      </div>

      <style>{`
        @keyframes spin { to { transform: rotate(360deg); } }
        @media (max-width: 768px) {
          .tracker-grid { grid-template-columns: 1fr !important; }
        }
      `}</style>
    </div>
  );
}